"""change num_pages to integer

Revision ID: 402b28dba4a8
Revises: 25bd0fcc29e2
Create Date: 2025-07-16 20:19:30.817564

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "402b28dba4a8"
down_revision: Union[str, Sequence[str], None] = "25bd0fcc29e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "num_pages",
        existing_type=sa.VARCHAR(length=500),
        type_=sa.Integer(),
        existing_nullable=False,
        postgresql_using="num_pages::integer",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "books",
        "num_pages",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=500),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
